;; port of usb_keyboard.h

(define key-a 4)
(define key-b 5)
(define key-c 6)
(define key-d 7)
(define key-e 8)
(define key-f 9)
(define key-g 10)
(define key-h 11)
(define key-i 12)
(define key-j 13)
(define key-k 14)
(define key-l 15)
(define key-m 16)
(define key-n 17)
(define key-o 18)
(define key-p 19)
(define key-q 20)
(define key-r 21)
(define key-s 22)
(define key-t 23)
(define key-u 24)
(define key-v 25)
(define key-w 26)
(define key-x 27)
(define key-y 28)
(define key-z 29)
(define key-semicolon 51)

(define key-comma 54)
(define key-period 55)
(define key-slash 56)
(define key-dash 45)
(define key-quote 52)

(define key-space 44)
(define key-backspace 42)
(define key-esc 41)
(define key-tab 43)
(define key-enter 40)

(define key-backslash 49)
(define key-backtick 53)

(define (modifier? keycode) (list? keycode))
(define (modify keycode) (list keycode))
(define (unmodify keycode) (car keycode))

(define mod-ctrl (modify #x01))
(define mod-shift (modify #x02))
(define mod-alt (modify #x04))
(define mod-gui (modify #x08))
(define mod-fn (modify #x16))
